services:
  excalidraw:
    build:
      context: ./excalidraw
      dockerfile: ../docker/excalidraw/Dockerfile
      args:
        VITE_APP_WS_SERVER_URL: "${VITE_APP_WS_SERVER_URL}"
    ports:
      - "127.0.0.1:9247:80"
    restart: unless-stopped

  excalidraw-room:
    image: excalidraw/excalidraw-room:sha-03ff435
    platform: linux/amd64
    ports:
      - "127.0.0.1:9248:80"
    restart: unless-stopped

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - excalidraw
      - excalidraw-room
    restart: unless-stopped
