services:
  excalidraw:
    build:
      context: ./excalidraw
      dockerfile: ../docker/excalidraw/Dockerfile
      args:
        VITE_APP_WS_SERVER_URL: http://localhost:9248
    ports:
      - "127.0.0.1:9247:80"
    restart: unless-stopped

  excalidraw-room:
    image: excalidraw/excalidraw-room:sha-03ff435
    platform: linux/amd64
    ports:
      - "127.0.0.1:9248:80"
    restart: unless-stopped
