map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80;
    server_name excalidraw.realunivlog.com;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name excalidraw.realunivlog.com;

    ssl_certificate /etc/letsencrypt/live/excalidraw.realunivlog.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/excalidraw.realunivlog.com/privkey.pem;

    location /socket.io/ {
        proxy_pass http://excalidraw-room:80;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    location / {
        proxy_pass http://excalidraw:8080;
    }
}
